name: Audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - "src-tauri/Cargo.lock"
      - "src-tauri/Cargo.toml"
  pull_request:
    branches:
      - main
    paths:
      - "src-tauri/Cargo.lock"
      - "src-tauri/Cargo.toml"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: audit
        working-directory: ./src-tauri
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
