name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libssl-dev
      - name: Install clippy with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path=src-tauri/Cargo.toml --all-targets --all-features -- -D warnings
          name: clippy
